# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

steps:
- checkout: self
  persistCredentials: true

- task: TouchdownBuildTask@1
  inputs:
    environment: 'PRODEXT'
    teamId: '26351'
    authType: 'OAuth'
    authId: 'f33d7964-39f5-461c-abf3-48791b86ca84'
    authKey: '_y24aH0mH-y0_-b7F_Wg4JV18-vye3eP-X'
    resourceFilePath: |
      */Microsoft.Teams.Apps.RemoteSupport/Resources/Strings.resx
      */Microsoft.Teams.Apps.RemoteSupport.Configuration/Resources/Strings.resx
    cultureMappingType: 'None'
    appendRelativeDir: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Show Touchdown output
      git status
      
      # Show post-processed output
      git status
      
      # Check in localized files to temp branch
      git checkout -b localization/build-$env:BUILD_BUILDID
      git add --all
      git config --global user.name "Build Pipeline"
      git commit -am "Localized resource files"
      git push --set-upstream origin localization/build-$env:BUILD_BUILDID